### ISSUE TITLE
Trained Models

### ISSUE THREAD

**Issue by ZeeRizvee** [Trami1995/YOLOv10#1]
Hi. Will you be releasing the trained models for YOLOv10 on COCO dataset anytime soon? It might also be helpful to include the model conversion script for YOLOv10 models under tools/model_converters.

**Comment by Trami1995** [comment]
Thank you for your interest, we will release our pretrained model in coming soon. And at that time, we also provide the converter scripts about original model to mmyolo model.

**Comment by clw5180** [comment]
When will the pretrained model be released? Thanks a lot !
