### ISSUE TITLE
cannot import error

### ISSUE THREAD

**Issue by RuizhouLiu** [Trami1995/YOLOv10#2]
When I run the code, a `CannotImportError` raised.  Details: `cannot import name 'YOLOv10NanoBackbone' from 'mmyolo.models.backbones.yolov10_backbone'`. 

In addition, `from .yolov10_backbone import YOLOv10NanoBackbone, YOLOv10SmallBackbone, YOLOv10MiddleBackbone, YOLOv10LargeBackbone, YOLOv10ExtremeBackbone` these module are not found.

Can I delete them?

**Comment by cdy-for-grad** [comment]
Thank you for interest. You can update the newest project. I fixed the import bug just now. Thank you

**Comment by Trami1995** [comment]
Thank you for interest. You can update the newest project. I fixed the import bug just now. Thank you
