### ISSUE TITLE
C2fCIB

### ISSUE THREAD

**Issue by zhouruiliangxian** [Trami1995/YOLOv10#3]
Is the parameter 'n' not pa
<img width="901" alt="屏幕截图 2024-07-07 235406" src="https://github.com/Trami1995/YOLOv10/assets/44407632/bb6a4df8-20ec-4bf1-aa02-b07506293956">
ssed in C2fCIB? It should be assigned as 'n = make_round(self.num_csp_blocks, self.deepen_factor)', right?

**Comment by Trami1995** [comment]
Thank you for your interest, the code is [refered](https://github.com/THU-MIG/yolov10/blob/cd2f79c70299c9041fb6d19617ef1296f47575b1/ultralytics/nn/modules/block.py#L760) from the public code
